server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        nodeName: node
#        instance-id: custom-service-id
        serviceName: ${spring.application.name}