server:
  port: 80

spring:
  application:
    name: cloud-consumer-order-openfeign
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}
        prefer-agent-address: true